<a href="https://colab.research.google.com/github/Sriva29/Biscuits-Over-Cookies/blob/main/Lab_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [3]:
# importing numpy
import numpy as np

In [8]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
a = np.array([1,2,3,5,0])
print (a)
print ("Are all elements in array a non-zero?", a.all())

[1 2 3 5 0]
Are all elements in array a non-zero? False


In [ ]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.

In [9]:
b = np.array([3, -1, 3, 7, 2])
print(b)
print("Are any of the arrays in array b non-zero?", b.any())

[ 3 -1  3  7  2]
Are any of the arrays in array b non-zero? True


In [ ]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.

In [10]:
c = np.array([0, 0, 0, 0])
print(c)
print("are any of the arrays of array c non-zero?", c.any())

[0 0 0 0]
are any of the arrays of array c non-zero? False


In [ ]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.

In [12]:
d = np.array([56, -2, 7])
print(d)
print("The amount of memory required to store array d is: ", d.itemsize*d.size)

[56 -2  7]
The amount of memory required to store array d is:  24


In [ ]:
# Create a numpy array with 10 zeros and print the array.

# Create a numpy array with 6 ones and print the array.

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]


In [16]:
e = np.zeros(10)
print(e)
f = np.ones(6)
print(f)
g = np.ones(12)*3
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [ ]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method


In [20]:
h = np.arange(8,21,1)
print("a numpy array of the integers from 8 to 20: ",h)
i = np.arange(8,21,2)
print("a numpy array of the even integers from 8 to 20: ",i)

a numpy array of the integers from 8 to 20:  [ 8  9 10 11 12 13 14 15 16 17 18 19 20]
a numpy array of the even integers from 8 to 20:  [ 8 10 12 14 16 18 20]


In [ ]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?


In [24]:
j = np.random.normal(2,0.5,100)
jmean = j.mean();
jstd = j.std();
jmax = j.max()
jmin = j.min()
print(f'The mean of j (100 random elements) is: {jmean}. The max of j is: {jmax}. The min of j is: {jmin}. The std of j array is: {jstd}')

k = np.random.normal(2,0.5,1000)
kmean = k.mean();
kstd = k.std();
kmax = k.max()
kmin = k.min()
print(f'The mean of k (1000 random elements) is: {kmean}. The max of k is: {kmax}. The min of k is: {kmin}. The std of k array is: {kstd}')

l = np.random.normal(2,0.5,1000000)
lmean = l.mean();
lstd = l.std();
lmax = l.max()
lmin = l.min()
print(f'The mean of l (1000000 random elements) is: {lmean}. The max of l is: {lmax}. The min of l is: {lmin}. The std of l array is: {lstd}')

The mean of j (100 random elements) is: 1.911605738316226. The max of j is: 3.0836650351275434. The min of j is: 0.8580118741346041. The std of j array is: 0.47780483163838794
The mean of k (1000 random elements) is: 1.9900173040668339. The max of k is: 4.069300201483303. The min of k is: 0.4431859883935232. The std of k array is: 0.4998781796625552
The mean of l (1000000 random elements) is: 1.999464542844919. The max of l is: 4.354955661259375. The min of l is: -0.38511851521882967. The std of l array is: 0.5001316451045876


The mean and the std appear to be very close to each other. There is an incremental increase in the mean an std, but it is very small.